### ISSUE TITLE
Getting error when syncing.

### ISSUE THREAD

**Issue by 4goodapp** [volsahin/volx-recyclerview-fast-scroll#3]
I get this error when I add `compile 'com.github.volsahin:volx-recyclerview-fast-scroll:v1.0.6'` and sync.

```
Error:Could not find com.android.support:recyclerview-v7:26.0.1.
Required by:
    project :app

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>
```

Any idea about this?

**Comment by volsahin** [comment]
What is the support library version that you use ?

**Comment by 4goodapp** [comment]
@volsahin v7:24.2.1

**Comment by volsahin** [comment]
Since volx is using support lib's autoSizeTextView which is available on 26.0.1, you should consider updating it.

**Comment by 4goodapp** [comment]
Okay, Thanks, I'll consider updating but, Is there an older version of the library that can work with 24.2.1 ?

**Comment by volsahin** [comment]
You can use v.1.0.5 or any releases before v1.0.6 . If support versions still not matching , you can use exclude feature in Gradle. This link may help https://stackoverflow.com/questions/44404308/android-force-gradle-to-include-only-one-version-of-a-library

**Comment by 4goodapp** [comment]
Edit the link, it's [https://stackoverflow.com/questions/44404308/android-force-gradle-to-include-only-one-version-of-a-library](https://stackoverflow.com/questions/44404308/android-force-gradle-to-include-only-one-version-of-a-library)

**Comment by volsahin** [comment]
@4goodapp Edited. Did it help with your issue ?

**Comment by 4goodapp** [comment]
Well not really, Still getting some issues with support library version (or whatever they are called). Nothing to do with your library. I think this as something to do with updating Android Studio.  I think I have to update everything to the latest version and see.

**Comment by 4goodapp** [comment]
@volsahin 
_offtopic_
Am haaving the same issue as [this one](https://stackoverflow.com/questions/45103230/failed-to-resolve-com-android-supportcardview-v726-0-0-android?answertab=votes#tab-top) but for 24.3.1
And now it seems like even people who are on 26.x.x are having same issue. What's causing this really?

**Comment by volsahin** [comment]
@4goodapp Can you try adding this in your app gradle (inside android tag). Based on the answer in this link ( https://stackoverflow.com/questions/45553058/android-manifest-merger-failed-gms-play-services-firebase )

`    configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '24.3.1'
            }
        }
    }
}`

**Comment by 4goodapp** [comment]
@volsahin 
Sorry for the Delay, I managed to make it work after lot of googling ... Don't even know what made work exactely. However, V 1.0.7  don't work, only V1.0.6 work, And when I run the app, it Crash with the following error:

```
...
E/AndroidRuntime: FATAL EXCEPTION: main

Process: com.helloct.helloct2, PID: 24540
java.lang.NullPointerException
at com.volcaniccoder.volxfastscroll.Volx.execute(Volx.java:90)
at com.volcaniccoder.volxfastscroll.Volx.<init>(Volx.java:85)
at com.volcaniccoder.volxfastscroll.Volx$Builder.build(Volx.java:529)
at com.helloct.helloct2.ZonesFragment.onCreateView(ZonesFragment.java:70)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
at android.view.View.measure(View.java:16749)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5295)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2439)
at android.view.View.measure(View.java:16749)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2080)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1176)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1380)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5993)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
at android.view.Choreographer.doCallbacks(Choreographer.java:574)
at android.view.Choreographer.doFrame(Choreographer.java:544)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
at android.os.Handler.handleCallback(Handler.java:733)
...

```

**Comment by volsahin** [comment]
@4goodapp Are you sure that you implemented it in correct way like in the sample app ? And do you see a warning log from VOLX on logcat?

**Comment by volsahin** [comment]
@4goodapp No reply. Issue closed
